<?php

declare(strict_types=1);
/**
 * GoogleAuth for FOSSBilling.
 *
 * Copyright 2026 Web Boomers (https://www.webboomers.in)
 * SPDX-License-Identifier: MIT
 */

namespace Box\Mod\Googleauth\Entity;

use Box\Mod\Googleauth\Repository\GoogleAccountRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * The link between a Google identity and a FOSSBilling customer.
 *
 * This is the only table the extension owns, and it holds the minimum needed to
 * recognise a returning customer:
 *
 * - `google_sub`   - Google's stable subject identifier, unique across the table
 * - `client_id`    - the FOSSBilling customer it belongs to, at most one link each
 * - `google_email` - metadata for the admin and profile screens only
 *
 * No access token, refresh token or ID token is stored. The extension
 * authenticates people; it never calls Google APIs on their behalf, so keeping
 * tokens would add risk and buy nothing.
 *
 * `client_id` is deliberately a plain column rather than a Doctrine association:
 * the extension stays decoupled from the core Client entity, and a customer
 * deleted by an administrator simply leaves a row that
 * {@see \Box\Mod\Googleauth\Service::onAfterAdminClientDelete()} cleans up.
 */
#[ORM\Entity(repositoryClass: GoogleAccountRepository::class)]
#[ORM\Table(name: 'googleauth_account')]
#[ORM\UniqueConstraint(name: 'uniq_googleauth_google_sub', columns: ['google_sub'])]
#[ORM\UniqueConstraint(name: 'uniq_googleauth_client_id', columns: ['client_id'])]
#[ORM\HasLifecycleCallbacks]
class GoogleAccount
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (the ID is generated by the database) */
    private ?int $id = null;

    #[ORM\Column(name: 'client_id', type: Types::BIGINT)]
    private int $clientId;

    #[ORM\Column(name: 'google_sub', type: Types::STRING, length: 255)]
    private string $googleSub;

    #[ORM\Column(name: 'google_email', type: Types::STRING, length: 255, nullable: true)]
    private ?string $googleEmail = null;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'updated_at', type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $updatedAt;

    #[ORM\Column(name: 'last_login_at', type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $lastLoginAt = null;

    public function __construct()
    {
        $now = new \DateTimeImmutable();
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): int
    {
        return $this->clientId;
    }

    public function setClientId(int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getGoogleSub(): string
    {
        return $this->googleSub;
    }

    public function setGoogleSub(string $googleSub): self
    {
        $this->googleSub = $googleSub;

        return $this;
    }

    public function getGoogleEmail(): ?string
    {
        return $this->googleEmail;
    }

    public function setGoogleEmail(?string $googleEmail): self
    {
        $this->googleEmail = $googleEmail === null ? null : strtolower(trim($googleEmail));

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function getLastLoginAt(): ?\DateTimeImmutable
    {
        return $this->lastLoginAt;
    }

    public function touchLastLogin(?\DateTimeImmutable $when = null): self
    {
        $this->lastLoginAt = $when ?? new \DateTimeImmutable();

        return $this;
    }

    /**
     * Safe for client- and admin-facing output: contains no token material.
     *
     * @return array<string, mixed>
     */
    public function toApiArray(): array
    {
        return [
            'id' => $this->id,
            'client_id' => $this->clientId,
            'google_email' => $this->googleEmail,
            'created_at' => $this->createdAt->format('Y-m-d H:i:s'),
            'updated_at' => $this->updatedAt->format('Y-m-d H:i:s'),
            'last_login_at' => $this->lastLoginAt?->format('Y-m-d H:i:s'),
        ];
    }
}
