<?php

declare(strict_types=1);
/**
 * GoogleAuth for FOSSBilling.
 *
 * Copyright 2026 Web Boomers (https://www.webboomers.in)
 * SPDX-License-Identifier: MIT
 */

namespace Box\Mod\Googleauth\Entity;

use Box\Mod\Googleauth\Repository\GoogleFlowRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * One in-flight OAuth authorization request.
 *
 * This does not live in the PHP session, and that is deliberate. FOSSBilling's
 * default `security.mode = 'strict'` marks the session cookie `SameSite=Strict`,
 * which browsers correctly withhold on the top-level navigation back from
 * accounts.google.com. A session-backed flow would therefore be invisible to the
 * callback on a stock installation, and every sign-in would fail.
 *
 * So the flow is stored here, looked up by the `state` value Google returns, and
 * bound to the browser by a separate short-lived `SameSite=Lax` cookie - Lax
 * being exactly the level that is sent on a top-level GET navigation.
 *
 * Both secrets are stored as SHA-256 hashes rather than in the clear: reading
 * this table gives an attacker nothing they could present back to the callback.
 * The row is deleted the moment it is used, and expires within minutes.
 */
#[ORM\Entity(repositoryClass: GoogleFlowRepository::class)]
#[ORM\Table(name: 'googleauth_flow')]
#[ORM\UniqueConstraint(name: 'uniq_googleauth_flow_state', columns: ['state_hash'])]
#[ORM\Index(name: 'idx_googleauth_flow_expires', columns: ['expires_at'])]
class GoogleFlow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::BIGINT)]
    /** @phpstan-ignore property.unusedType (the ID is generated by the database) */
    private ?int $id = null;

    /** SHA-256 of the OAuth `state`. The lookup key. */
    #[ORM\Column(name: 'state_hash', type: Types::STRING, length: 64)]
    private string $stateHash;

    /** SHA-256 of the value in the browser's SameSite=Lax correlation cookie. */
    #[ORM\Column(name: 'correlation_hash', type: Types::STRING, length: 64)]
    private string $correlationHash;

    #[ORM\Column(name: 'nonce', type: Types::STRING, length: 128)]
    private string $nonce;

    #[ORM\Column(name: 'code_verifier', type: Types::STRING, length: 128)]
    private string $codeVerifier;

    #[ORM\Column(name: 'intent', type: Types::STRING, length: 16)]
    private string $intent;

    #[ORM\Column(name: 'return_to', type: Types::STRING, length: 512)]
    private string $returnTo = '/';

    /** Set only for the "link" intent: the customer who started it. */
    #[ORM\Column(name: 'client_id', type: Types::BIGINT, nullable: true)]
    private ?int $clientId = null;

    #[ORM\Column(name: 'created_at', type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'expires_at', type: Types::DATETIME_IMMUTABLE)]
    private \DateTimeImmutable $expiresAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public static function hash(string $value): string
    {
        return hash('sha256', $value);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStateHash(): string
    {
        return $this->stateHash;
    }

    public function setStateHash(string $stateHash): self
    {
        $this->stateHash = $stateHash;

        return $this;
    }

    public function getCorrelationHash(): string
    {
        return $this->correlationHash;
    }

    public function setCorrelationHash(string $correlationHash): self
    {
        $this->correlationHash = $correlationHash;

        return $this;
    }

    public function getNonce(): string
    {
        return $this->nonce;
    }

    public function setNonce(string $nonce): self
    {
        $this->nonce = $nonce;

        return $this;
    }

    public function getCodeVerifier(): string
    {
        return $this->codeVerifier;
    }

    public function setCodeVerifier(string $codeVerifier): self
    {
        $this->codeVerifier = $codeVerifier;

        return $this;
    }

    public function getIntent(): string
    {
        return $this->intent;
    }

    public function setIntent(string $intent): self
    {
        $this->intent = $intent;

        return $this;
    }

    public function getReturnTo(): string
    {
        return $this->returnTo;
    }

    public function setReturnTo(string $returnTo): self
    {
        $this->returnTo = substr($returnTo, 0, 512);

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->clientId;
    }

    public function setClientId(?int $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getExpiresAt(): \DateTimeImmutable
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(\DateTimeImmutable $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }
}
